[workspace]
resolver = "2"
members = [
    "crates/dllm-core",
    "crates/dllm-net",
    "crates/dllm-store",
    "crates/dllm-serve",
    "apps/dllm",
]

[workspace.dependencies]
tokio = { version = "1.53", features = ["full"] }
axum = { version = "0.8", features = ["json"] }
tower-http = { version = "0.7", features = ["fs"] }
tokio-stream = { version = "0.1" }
async-stream = { version = "0.3" }
quinn = { version = "0.11" }
rustls = { version = "=0.23.44" }
tokio-rustls = { version = "0.26" }
rcgen = { version = "0.14" }
mdns-sd = { version = "0.21" }
rusqlite = { version = "0.40", features = ["bundled"] }
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
postcard = { version = "1", features = ["alloc"] }
flume = { version = "0.11" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = { version = "1" }
thiserror = { version = "2" }
